export const initialFactoryData = {
    rawMaterials: [
        {
            id: 'rm-1',
            name: 'Corn (جواری / جوارت)',
            category: 'Grains',
            stockKg: 14500,
            unitPrice: 24, // 24 AFN per kg
            supplierId: 'sup-1',
            supplierName: 'حاجی بشیر احمد (غله جات قندهار)',
            dateAdded: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
            notes: 'دانه جواری درجه یک زرد',
        },
        {
            id: 'rm-2',
            name: 'Soybean Meal (کنجاره سویا)',
            category: 'Protein',
            stockKg: 9200,
            unitPrice: 48,
            supplierId: 'sup-2',
            supplierName: 'شرکت بازرگانی شمس هرات',
            dateAdded: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
            notes: 'پروتین ۴۶ فیصد وارداتی',
        },
        {
            id: 'rm-3',
            name: 'Oil Cake (کنجاره پنبه دانه / پخته)',
            category: 'Protein',
            stockKg: 6400,
            unitPrice: 32,
            supplierId: 'sup-3',
            supplierName: 'تولیدی روغن و کنجاره مزار شریف',
            dateAdded: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
            notes: 'کنجاره میده شده با کیفیت',
        },
        {
            id: 'rm-4',
            name: 'Petrol & Diesel Oil (تیل دیزل جنراتور و موتر)',
            category: 'Fuel',
            stockKg: 1200, // 1200 Liters / Kg
            unitPrice: 65,
            supplierId: 'sup-4',
            supplierName: 'تانک تیل برادران احمدی',
            dateAdded: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
            notes: 'دیزل سوپر برای جنراتور کارخانه',
        },
        {
            id: 'rm-5',
            name: 'Wheat Bran (سبوس گندم)',
            category: 'Fiber',
            stockKg: 4000,
            unitPrice: 18,
            supplierId: 'sup-1',
            supplierName: 'حاجی بشیر احمد (غله جات قندهار)',
            dateAdded: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
            notes: 'سبوس درشت آسیاب آرد',
        },
        {
            id: 'rm-6',
            name: 'Premix & Vitamins (پری‌میکس و ویتامین مرغداری)',
            category: 'Supplements',
            stockKg: 850,
            unitPrice: 120,
            supplierId: 'sup-2',
            supplierName: 'شرکت بازرگانی شمس هرات',
            dateAdded: new Date(Date.now() - 6 * 86400000).toISOString().split('T')[0],
            notes: 'مکمل ویتامینه ۲.۵ فیصد مخصوص جوجه گوشتی',
        },
    ],
    processedStock: [
        {
            id: 'ps-1',
            name: 'Broiler Starter Feed (دانه آغازین برویلر - پری استارتر)',
            formulaId: 'form-1',
            stockKg: 8500, // 170 bags
            averageCostPerKg: 34.8,
            lastUpdated: new Date().toISOString().split('T')[0],
        },
        {
            id: 'ps-2',
            name: 'Broiler Grower Feed (دانه رشد برویلر)',
            formulaId: 'form-2',
            stockKg: 12000, // 240 bags
            averageCostPerKg: 31.5,
            lastUpdated: new Date().toISOString().split('T')[0],
        },
        {
            id: 'ps-3',
            name: 'Layer Hen Feed (دانه مرغ تخمی)',
            formulaId: 'form-3',
            stockKg: 5000, // 100 bags
            averageCostPerKg: 28.2,
            lastUpdated: new Date().toISOString().split('T')[0],
        },
    ],
    suppliers: [
        {
            id: 'sup-1',
            name: 'حاجی بشیر احمد (غله جات قندهار)',
            phone: '0700123456',
            address: 'مارکیت غله جات، قندهار',
            totalPurchasedAmount: 420000,
            totalPaid: 320000,
            balanceOwed: 100000, // We owe 100,000 AFN
            transactions: [
                {
                    id: 'st-1',
                    date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
                    type: 'purchase',
                    description: 'خرید جواری و سبوس گندم',
                    amount: 420000,
                    paidAmount: 320000,
                    remainingAmount: 100000,
                },
            ],
            createdAt: '2026-09-01',
        },
        {
            id: 'sup-2',
            name: 'شرکت بازرگانی شمس هرات',
            phone: '0799887766',
            address: 'شهرک صنعتی، هرات',
            totalPurchasedAmount: 543600,
            totalPaid: 450000,
            balanceOwed: 93600,
            transactions: [
                {
                    id: 'st-2',
                    date: new Date(Date.now() - 6 * 86400000).toISOString().split('T')[0],
                    type: 'purchase',
                    description: 'خرید سویا و پری‌میکس ویتامینه',
                    amount: 543600,
                    paidAmount: 450000,
                    remainingAmount: 93600,
                },
            ],
            createdAt: '2026-09-03',
        },
        {
            id: 'sup-3',
            name: 'تولیدی روغن و کنجاره مزار شریف',
            phone: '0788334455',
            address: 'سرک بلخ، مزار شریف',
            totalPurchasedAmount: 204800,
            totalPaid: 150000,
            balanceOwed: 54800,
            transactions: [
                {
                    id: 'st-3',
                    date: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
                    type: 'purchase',
                    description: 'خرید ۶۴۰۰ کیلو کنجاره پنبه دانه',
                    amount: 204800,
                    paidAmount: 150000,
                    remainingAmount: 54800,
                },
            ],
            createdAt: '2026-09-05',
        },
        {
            id: 'sup-4',
            name: 'تانک تیل برادران احمدی',
            phone: '0777112233',
            address: 'سرک عمومی فابریکات',
            totalPurchasedAmount: 78000,
            totalPaid: 78000,
            balanceOwed: 0, // Fully paid
            transactions: [
                {
                    id: 'st-4',
                    date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
                    type: 'purchase',
                    description: 'خرید تیل دیزل ۱۲۰۰ لیتر برای جنراتور',
                    amount: 78000,
                    paidAmount: 78000,
                    remainingAmount: 0,
                },
            ],
            createdAt: '2026-09-10',
        },
    ],
    customers: [
        {
            id: 'cust-1',
            name: 'فارم مرغداری برکت (حاجی نقیب الله)',
            phone: '0700554433',
            address: 'ولسوالی بگرامی، کابل',
            totalPurchasedAmount: 380000,
            totalPaid: 260000,
            balanceOwed: 120000, // Customer owes us 120,000 AFN
            transactions: [
                {
                    id: 'ct-1',
                    date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
                    type: 'sale',
                    description: 'فروش ۴۰۰۰ کیلو دانه رشد (۸۰ بوجی)',
                    amount: 380000,
                    paidAmount: 260000,
                    remainingAmount: 120000,
                },
            ],
            createdAt: '2026-09-02',
        },
        {
            id: 'cust-2',
            name: 'مرغداری صفا (انجنیر وحید)',
            phone: '0799112233',
            address: 'پلچرخی، کابل',
            totalPurchasedAmount: 220000,
            totalPaid: 170000,
            balanceOwed: 50000,
            transactions: [
                {
                    id: 'ct-2',
                    date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
                    type: 'sale',
                    description: 'فروش ۵۰ بوجی دانه آغازین برویلر',
                    amount: 220000,
                    paidAmount: 170000,
                    remainingAmount: 50000,
                },
            ],
            createdAt: '2026-09-06',
        },
        {
            id: 'cust-3',
            name: 'فارم مرغان تخمی نورستان (حاجی زلمی)',
            phone: '0786556677',
            address: 'سرک دارالامان، کابل',
            totalPurchasedAmount: 180000,
            totalPaid: 180000,
            balanceOwed: 0,
            transactions: [
                {
                    id: 'ct-3',
                    date: new Date().toISOString().split('T')[0],
                    type: 'sale',
                    description: 'فروش ۳ تن دانه مرغ تخمی (نقد پرداخت شد)',
                    amount: 180000,
                    paidAmount: 180000,
                    remainingAmount: 0,
                },
            ],
            createdAt: '2026-09-12',
        },
    ],
    formulas: [
        {
            id: 'form-1',
            name: 'Broiler Starter Feed (دانه آغازین برویلر)',
            description: 'فرمول استاندارد روز ۱ تا ۱۵ جوجه گوشتی با پروتئین بالا',
            ingredients: [
                { rawMaterialId: 'rm-1', rawMaterialName: 'Corn (جواری)', weightKg: 550, costPerKg: 24, totalCost: 13200 },
                { rawMaterialId: 'rm-2', rawMaterialName: 'Soybean Meal (کنجاره سویا)', weightKg: 350, costPerKg: 48, totalCost: 16800 },
                { rawMaterialId: 'rm-3', rawMaterialName: 'Oil Cake (کنجاره پنبه دانه)', weightKg: 75, costPerKg: 32, totalCost: 2400 },
                { rawMaterialId: 'rm-6', rawMaterialName: 'Premix & Vitamins (پری‌میکس)', weightKg: 25, costPerKg: 120, totalCost: 3000 },
            ],
            totalWeightKg: 1000,
            totalBatchCost: 35400,
            costPerKg: 35.4,
            createdDate: '2026-09-10',
        },
        {
            id: 'form-2',
            name: 'Broiler Grower Feed (دانه رشد برویلر)',
            description: 'فرمول رشد روز ۱۶ تا ۳۰ با ضریب تبدیل عالی',
            ingredients: [
                { rawMaterialId: 'rm-1', rawMaterialName: 'Corn (جواری)', weightKg: 600, costPerKg: 24, totalCost: 14400 },
                { rawMaterialId: 'rm-2', rawMaterialName: 'Soybean Meal (کنجاره سویا)', weightKg: 280, costPerKg: 48, totalCost: 13440 },
                { rawMaterialId: 'rm-3', rawMaterialName: 'Oil Cake (کنجاره پنبه دانه)', weightKg: 95, costPerKg: 32, totalCost: 3040 },
                { rawMaterialId: 'rm-6', rawMaterialName: 'Premix & Vitamins (پری‌میکس)', weightKg: 25, costPerKg: 120, totalCost: 3000 },
            ],
            totalWeightKg: 1000,
            totalBatchCost: 33880,
            costPerKg: 33.88,
            createdDate: '2026-09-11',
        },
    ],
    productionBatches: [
        {
            id: 'batch-1',
            formulaId: 'form-1',
            formulaName: 'Broiler Starter Feed (دانه آغازین برویلر)',
            date: new Date().toISOString().split('T')[0], // Today
            totalWeightKg: 3000, // 3 tons produced today
            costPerKg: 35.4,
            totalCost: 106200,
            operatorName: 'استاد احمدالله (مسئول خط تولید)',
            notes: 'تولید شیفت صبح - ۶۰ بوجی بسته بندی شد',
        },
        {
            id: 'batch-2',
            formulaId: 'form-2',
            formulaName: 'Broiler Grower Feed (دانه رشد برویلر)',
            date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
            totalWeightKg: 5000,
            costPerKg: 33.88,
            totalCost: 169400,
            operatorName: 'استاد احمدالله',
            notes: 'تولید ۱۰۰ بوجی دانه رشد',
        },
    ],
    sales: [
        {
            id: 'sale-1',
            date: new Date().toISOString().split('T')[0],
            customerId: 'cust-3',
            customerName: 'فارم مرغان تخمی نورستان (حاجی زلمی)',
            customerPhone: '0786556677',
            productId: 'ps-3',
            productName: 'Layer Hen Feed (دانه مرغ تخمی)',
            unitType: 'ton',
            unitQuantity: 3,
            quantityKg: 3000, // 3 tons
            salePricePerUnit: 60000, // 60,000 AFN per ton
            totalAmount: 180000,
            costRatePerKg: 28.2,
            totalCostOfGoods: 84600,
            profit: 95400,
            paidAmount: 180000,
            remainingAmount: 0,
            notes: 'فروش ۳ تن نقد',
        },
        {
            id: 'sale-2',
            date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
            customerId: 'cust-2',
            customerName: 'مرغداری صفا (انجنیر وحید)',
            customerPhone: '0799112233',
            productId: 'ps-1',
            productName: 'Broiler Starter Feed (دانه آغازین برویلر)',
            unitType: 'bag',
            unitQuantity: 50,
            quantityKg: 2500, // 50 bags = 2500 kg
            salePricePerUnit: 4400, // 4,400 AFN per bag
            totalAmount: 220000,
            costRatePerKg: 34.8,
            totalCostOfGoods: 87000,
            profit: 133000,
            paidAmount: 170000,
            remainingAmount: 50000,
            notes: '۵۰ بوجی - ۵۰ هزار باقی‌داری مانده',
        },
        {
            id: 'sale-3',
            date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
            customerId: 'cust-1',
            customerName: 'فارم مرغداری برکت (حاجی نقیب الله)',
            customerPhone: '0700554433',
            productId: 'ps-2',
            productName: 'Broiler Grower Feed (دانه رشد برویلر)',
            unitType: 'bag',
            unitQuantity: 80,
            quantityKg: 4000,
            salePricePerUnit: 4750,
            totalAmount: 380000,
            costRatePerKg: 31.5,
            totalCostOfGoods: 126000,
            profit: 254000,
            paidAmount: 260000,
            remainingAmount: 120000,
            notes: '۸۰ بوجی - ۱۲۰ هزار باقی‌داری مانده',
        },
    ],
    expenses: [
        {
            id: 'exp-1',
            date: new Date().toISOString().split('T')[0],
            category: 'fuel',
            description: 'خرید تیل دیزل جهت روشن نگهداشتن جنراتور کارخانه',
            amount: 15000,
            paidBy: 'مسئول مالی',
            notes: 'فاکتور نمبر ۱۰۲',
        },
        {
            id: 'exp-2',
            date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
            category: 'salary',
            description: 'معاش هفته‌وار کارگران خط پروسس و آسیاب دانه',
            amount: 32000,
            paidBy: 'مدیر اداری',
            notes: '۴ نفر کارگر شیفت روز',
        },
        {
            id: 'exp-3',
            date: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
            category: 'food',
            description: 'تهیه نان چاشت و چای پرسونل کارخانه',
            amount: 4500,
            paidBy: 'آشپز کارخانه',
        },
        {
            id: 'exp-4',
            date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
            category: 'electricity',
            description: 'پرداخت بل برق فابریکه (برق صنعتی د افغانستان برشنا شرکت)',
            amount: 28000,
            paidBy: 'حسابدار',
            notes: 'بل دوره اسد',
        },
        {
            id: 'exp-5',
            date: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
            category: 'maintenance',
            description: 'تعویض چکش‌های میده کننده (آسیاب) و گریس کاری بلبرینگ‌ها',
            amount: 12000,
            paidBy: 'تکنیشن ماشین',
        },
    ],
    cashInHand: 435000, // 435,000 AFN cash balance
};
